### ISSUE TITLE
[FEATURE] Submit RetryPushData immediately encountering DIRECT_MEMORY exceeding of worker

### ISSUE THREAD

**Issue by miaoxf** [alibaba/celeborn#103]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when DIRECT_MEMORY_COUNTER of netty exceeds the offheapMemoryCriticalThreshold, worker will set AutoRead from true to false in GlobalChannelLimiter, which will not fire ChannelRead, and, in turn, worker won't reply any message to executor, so shuffle writer will wait until timeout without reviving and requesting for new slots to submit RetryPushData.

### Describe the solution you'd like
Shall we reply some specific message to executor when worker finds the exceeding of DIRECT_MEMORY, so executor can  submit RetryPushData immediately?

### Describe alternatives you've considered
I just expand RSS_WORKER_OFFHEAP_MEMORY of worker for now.

/cc @who-need-to-know
@FMX 
/assign @who-can-help-you

**Comment by FMX** [comment]
@miaoxf 
The worker`s minimum direct memory should be larger than num of cores * 16(MB). Because we use pooled memory allocator.
Can you share your host information and configurations?

**Comment by waitinfuture** [comment]
Seems like a bug, I think we should add more test cases @FMX

**Comment by FMX** [comment]
@miaoxf  
If you are convenient, you can join the [chat](https://gitter.im/RemoteShuffleServiceCommunity/community).
I think there is an alternative solution rather than changing RSS_WORKER_OFFHEAP_MEMORY.

**Comment by miaoxf** [comment]
with pleasure
