### ISSUE TITLE
[FEATURE] Worker has many indicators, and Prometheus has been connected. Is there any plan to analyze the indicators in detail

### ISSUE THREAD

**Issue by CCweixiao** [alibaba/celeborn#29]
我们已经采集指标到普罗米修斯，但是面对这么多指标，比较困扰，是否有计划对指标进行较为详细的剖析，我们也好有针对性地关注这些指标的不同表现，然后去优化RSS服务，或进行隐患诊断。

另外 是否有计划提供grafana的监控模版。

非常感谢！

We have collected indicators to Prometheus, but in the face of so many indicators, it is difficult to know whether there is a plan to carry out a detailed analysis of indicators, so that we can focus on the different performance of these indicators, and then optimize RSS service or carry out hidden trouble diagnosis. 
In addition, is there any plan to provide the monitoring template of Grafana? 
Thanks very much!

**Comment by waitinfuture** [comment]
我们有计划优化监控模块，增加指标说明和补文档；grafana监控模板这块还没有详细讨论过。关于监控你们有好的想法欢迎讨论和提pr。

**Comment by FMX** [comment]
Done and we have provide grafana dashboard.
