### ISSUE TITLE
[FEATURE] Load balance improvements.

### ISSUE THREAD

**Issue by FMX** [alibaba/celeborn#40]
### Describe alternatives you've considered

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by lichaojacobs** [comment]
Is there any ability that writers can send data to multiple workers dynamically when worker found there exists skewed partitions?

**Comment by waitinfuture** [comment]
> 

The newest code has overcome this issue by splitting partition files when the file is too large, regardless whether the partition is skew or not. BTW, we support AQE now.

**Comment by FMX** [comment]
Done.
