### ISSUE TITLE
[BUG] could not run select count(*) successful

### ISSUE THREAD

**Issue by xudalei1977** [alibaba/celeborn#475]
### What is the bug(with logs or screenshots)?

start the spark-sql as:
spark-sql \
--master yarn \
--deploy-mode client \
--num-executors 5 \
--executor-cores 2 \
--executor-memory 8G \
--driver-cores 1 \
--driver-memory 4G \
--conf "spark.dynamicAllocation.enabled=false" \
--conf "spark.sql.debug.maxToStringFields=500" \
--conf "spark.shuffle.manager=org.apache.spark.shuffle.rss.RssShuffleManager" \
--conf "spark.serializer=org.apache.spark.serializer.KryoSerializer" \
--conf "spark.rss.master.address=ip-10-0-0-151.ec2.internal:9097" \
--conf "spark.shuffle.service.enabled=false" \
--conf "spark.rss.push.data.replicate=true" \
--conf "spark.sql.adaptive.localShuffleReader.enabled=false" \
--conf "spark.sql.adaptive.enabled=true" \
--conf "spark.sql.adaptive.skewJoin.enabled=true"

spark-sql> select * from rss_1;
1
1
Time taken: 6.193 seconds, Fetched 2 row(s)
spark-sql> select count(*) from rss_1;
2305843014045532161
Time taken: 2.832 seconds, Fetched 1 row(s)

### How to reproduce the bug?
Steps to reproduce the bug.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by FMX** [comment]
@xudalei1977  What branch do you use while running "select count(*) "? Can you share your build's git commit id?

**Comment by xudalei1977** [comment]
> 

the master branch, follow the readme to build.

**Comment by xudalei1977** [comment]
> @xudalei1977 What branch do you use while running "select count(*) "? Can you share your build's git commit id?

6d9b81957e3122673c2a10731e9a3b098a03900b

**Comment by waitinfuture** [comment]
I didn't reproduce the bug.
![image](https://user-images.githubusercontent.com/948245/187142659-be2c9bd4-4d99-4502-bbf8-a468ee29d606.png)
The following log proves RSS is used
```
22/08/29 15:02:28,469 INFO [dispatcher-event-loop-45] Master: Offer slots successfully for 1 reducers of application_1661174368345_0182-0 on 1 workers.
22/08/29 15:02:28,470 INFO [dispatcher-event-loop-45] Master: Offered extra 2 slots for application_1661174368345_0182-0
22/08/29 15:02:28,735 INFO [dispatcher-event-loop-47] Master: [handleReleaseSlots] Release all slots of application_1661174368345_0182-0
```

**Comment by xudalei1977** [comment]
> 

i use AWS EMR 6.5.0, Spark 3.1.2,

spark-sql> select * from rss_1;
22/08/29 14:24:12 WARN SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
1
1
Time taken: 10.281 seconds, Fetched 2 row(s)
spark-sql> select count(*) from rss_1;
2305843018340499456
Time taken: 11.333 seconds, Fetched 1 row(s)
spark-sql>
