### ISSUE TITLE
RSS with spark dynamic allocation

### ISSUE THREAD

**Issue by fhalde** [alibaba/celeborn#480]
The docs don't mention this but if i were to setup an RSS for my spark setup, does it mean i can leverage sparks dynamic allocation? currently according to spark documentation, if i want to set dynamic allocation I need to be able to set `spark.shuffle.service.enabled` which defeats the point of having a RSS setup

There also seems to be an option of `spark.dynamicAllocation.shuffleTracking.enabled`

**Comment by waitinfuture** [comment]
Hi, RSS supports spark's dynamic allocation, see the following section in README:
```
Support Spark Dynamic Allocation
We provide a patch to enable users to use Spark with both dynamic allocation and Remote Shuffle Service. For Spark2.x check [Spark2 Patch](https://github.com/alibaba/RemoteShuffleService/blob/main/assets/spark-patch/RSS_RDA_spark2.patch).
For Spark3.x check [Spark3 Patch](https://github.com/alibaba/RemoteShuffleService/blob/main/assets/spark-patch/RSS_RDA_spark3.patch).
```
To enable DRA with RSS, after applying the above patches, spark.shuffle.service.enabled should be set to false, and there is no need to set spark.dynamicAllocation.shuffleTracking.enabled
