### ISSUE TITLE
[K8S] worker starts,File does not exist

### ISSUE THREAD

**Issue by liugs0213** [alibaba/celeborn#738]
### What is the bug(with logs or screenshots)?
Multiple workers using the same machine checkDiskReadAndWrite has the following exception.
![image](https://user-images.githubusercontent.com/55676558/194710333-ce1c3a22-edb3-44dd-8858-3f39a91e59af.png)
In checkDiskReadAndWrite, different workers may operate on the same file in the same timestamp. Temporarily changing the timestamp to uuid will not cause this exception.
![image](https://user-images.githubusercontent.com/55676558/194710569-3090098d-5d52-4b61-9531-429bd12a8a15.png)

### How to reproduce the bug?
k8s environment, one machine multiple workers.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by FMX** [comment]
Hi @liugs0213 , A worker can write multiple data dirs. So there is no need to start multiple workers on the same node. 
Can you share your scenario of deploying multiple workers on the same node?

**Comment by liugs0213** [comment]
> Hi @liugs0213 , A worker can write multiple data dirs. So there is no need to start multiple workers on the same node. Can you share your scenario of deploying multiple workers on the same node?
In the k8s environment, for fear of the impact of rss workers on other services, some machines are used to deploy rss workers independently. Currently, one machine is deployed with 3-5 workers.

**Comment by liugs0213** [comment]
> > Hi @liugs0213 , A worker can write multiple data dirs. So there is no need to start multiple workers on the same node. Can you share your scenario of deploying multiple workers on the same node?
> > In the k8s environment, for fear of the impact of rss workers on other services, some machines are used to deploy rss workers independently. Currently, one machine is deployed with 3-5 workers.

In the k8s environment, for fear of the impact of rss workers on other services, some machines are used to deploy rss workers independently. Currently, one machine is deployed with 3-5 workers

**Comment by liugs0213** [comment]
> Hi @liugs0213 , A worker can write multiple data dirs. So there is no need to start multiple workers on the same node. Can you share your scenario of deploying multiple workers on the same node?

In the k8s environment, for fear of the impact of rss workers on other services, some machines are used to deploy rss workers independently. Currently, one machine is deployed with 3-5 workers

**Comment by FMX** [comment]
I think you can refer to our solution for K8S by adding persistent volume claims to isolate disks.

**Comment by liugs0213** [comment]
> I think you can refer to our solution for K8S by adding persistent volume claims to isolate disks.

ok, thank you.
