### ISSUE TITLE
[FEATURE] Support DFS as the shuffle data storage

### ISSUE THREAD

**Issue by Gustfh** [alibaba/celeborn#74]
Add support DFS for the shuffle data storage, such as HDFS, Alluxio. so rss will not care about the disk healthy, the replication. and  also the DFS could take the pressure of shuffle read.

**Comment by FMX** [comment]
@Gustfh  Hi, thanks for your advice.
We had supported HDFS before and found that performance on HDFS is unacceptable.
We are working on supporting AliLFS now.

**Comment by Gustfh** [comment]
i think we should open an abstract for dfs storage or compose storage, so other people could implement different storage as their requirement.

**Comment by FMX** [comment]
OK, I think you are right. Let me propose a draft.

**Comment by FMX** [comment]
Check #146  and I'll close this pr.
