### ISSUE TITLE
[REFACTOR] Create file twice cause Worker stuck and trimFlush not work

### ISSUE THREAD

**Issue by AngersZhuuuu** [alibaba/celeborn#865]
### Describe the intention you'd like

1. Same partition and epoch twice caused by #863 
2. Create file throw exception and report an device error since file already exists
3. device related directories 's file writer attach a exception
4. device error cause flush interrupt and disk io slow, memory increase
5. Memory increase cause pause push data and pause replicate data
6. during pausing receiving data trim `onTrim` and flush all file writers to memory
7. FileWriter with exception also in the flush behavior and throw exception, flush behavior stoped.
8. Memory can't drop

<img width="1732" alt="截屏2022-10-27 下午6 32 14" src="https://user-images.githubusercontent.com/46485123/198262305-61078dd5-119a-4664-be6b-2702cc29a25a.png">

- [x] #863 
- [x] #866
- [x] #867
- [x] #879
- [x] #880
- [x] #921
- [x] #932

/cc @who-need-to-know

/assign @who-can-help-you

**Comment by AngersZhuuuu** [comment]
cc @nafiyAix

**Comment by waitinfuture** [comment]
Could you please describe more detail about the problem?
